package style95

import akka.actor.{Actor, ActorRef, Props}
import style95.Container.ContainerProperty

import scala.concurrent.duration._

object Container {
  final case class ActivationMessage(
      requester: ActorRef, // the sender of this activation message, used for routing
      userStart: Long, // (nano timestamp) when the request was generated by user
      invokeStart: Long // (nano timestamp) when the request was sent to a container
  ) {
    def invokeAt(t: Long): ActivationMessage =
      ActivationMessage(requester, userStart, t)
  }

  final case class WorkDone(message: ActivationMessage)

  final case class ContainerStatus(ready: Boolean)

  final case object ContainerCreated

  final case class ContainerProperty(initialDelay: FiniteDuration,
                                     execTime: FiniteDuration)

  def props(simulator: ActorRef, property: ContainerProperty): Props =
    Props(new Container(simulator, property))
}

class Container(val simulator: ActorRef, property: ContainerProperty)
    extends Actor {

  import Container._
  import context.{system, dispatcher}

  system.scheduler.scheduleOnce(property.initialDelay) {
    simulator ! ContainerCreated
  }

  override def receive: Receive = {
    case msg: ActivationMessage =>
      system.scheduler.scheduleOnce(property.execTime) {
        simulator ! WorkDone(msg)
      }
  }
}
